import { Analytics } from "@vercel/analytics/react";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <script
        async
        src="https://lynx-umami.vercel.app/script.js"
        data-website-id="c202dd8c-9dcc-4f9f-9a5b-1966e3e61723"
      ></script>
      <body>{children}</body>
      <Analytics />
    </html>
  );
}
